### ISSUE TITLE
make it official

### ISSUE THREAD

**Issue by sils** [alexmurray/flycheck-coala#1]
Hi,

we'd be interested in pulling this plugin in an official repository, with that we'd regularly check if it works if coala changes and help you maintain it. As part of that I think it'd be good to add CI to some degree if this is possible for such a small thing, just to be able to continuously validate it. (We're thinking about some concepts to make sure all plugins are always up to date.)

Any interest/objections?

**Comment by alexmurray** [comment]
Hi - sorry for the delay in replying - sure I would be happy to have it officially maintained - I am not using Coala much myself so this sounds like a good idea.

**Comment by sils** [comment]
Cool, thanks! We'll do that.

**Comment by sils** [comment]
Hi, I've migrated it to a coala-analyzer repository, @alexmurray would you mind granting us the right to publish your source code under a free software license? You haven't specified one in the repository.

**Comment by sils** [comment]
new repo on https://github.com/coala-analyzer/coala-emacs

**Comment by alexmurray** [comment]
As noted in the source code, it is already licensed under GPL3+

**Comment by sils** [comment]
ah sorry didn't see it

**Comment by sils** [comment]
thanks
